export const AUDIT_EVENTS = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  PASSWORD_RESET: "PASSWORD_RESET",
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_DELETED: "LEAD_DELETED",
  LEADS_BULK_IMPORTED: "LEADS_BULK_IMPORTED",
  LEAD_RESEARCH_TRIGGERED: "LEAD_RESEARCH_TRIGGERED",
  LEAD_PIPELINE_ADVANCED: "LEAD_PIPELINE_ADVANCED",
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
  CAMPAIGN_STARTED: "CAMPAIGN_STARTED",
  CAMPAIGN_PAUSED: "CAMPAIGN_PAUSED",
  CAMPAIGN_COMPLETED: "CAMPAIGN_COMPLETED",
  CAMPAIGN_DELETED: "CAMPAIGN_DELETED",
  EMAIL_SENT: "EMAIL_SENT",
  EMAIL_FAILED: "EMAIL_FAILED",
  COMPLIANCE_BLOCKED: "COMPLIANCE_BLOCKED",
  AUTO_SEND_BLOCKED: "AUTO_SEND_BLOCKED",
  LEAD_SCORED: "LEAD_SCORED",
  REPLY_RECEIVED: "REPLY_RECEIVED",
  REPLY_DRAFT_SENT: "REPLY_DRAFT_SENT",
  REPLY_REVIEWED: "REPLY_REVIEWED",
  REPLY_MEETING_LINK_INJECTED: "REPLY_MEETING_LINK_INJECTED",
  REPLY_OBJECTION_HANDLED: "REPLY_OBJECTION_HANDLED",
  QUEUE_JOB_FAILED: "QUEUE_JOB_FAILED",
  QUEUE_JOB_COMPLETED: "QUEUE_JOB_COMPLETED",
  API_KEY_CREATED: "API_KEY_CREATED",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  LEARNING_EVENT_RESOLVED: "LEARNING_EVENT_RESOLVED",
  LEARNING_EVENT_DISMISSED: "LEARNING_EVENT_DISMISSED",
  DELIVERABILITY_EVENT_CREATED: "DELIVERABILITY_EVENT_CREATED",
  DOMAIN_HEALTH_UPDATED: "DOMAIN_HEALTH_UPDATED",
  DOMAIN_ADDED: "DOMAIN_ADDED",
  DOMAIN_REMOVED: "DOMAIN_REMOVED",
  MESSAGE_APPROVED: "MESSAGE_APPROVED",
  MESSAGE_REJECTED: "MESSAGE_REJECTED",
  BRAND_SETTINGS_UPDATED: "BRAND_SETTINGS_UPDATED",
  SUPPRESSION_ADDED: "SUPPRESSION_ADDED",
  SUPPRESSION_REMOVED: "SUPPRESSION_REMOVED",
} as const;

export type AuditEvent =
  (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];

export const LEARNING_EVENT_TYPES = {
  REVIEW_FLAGGED: "REVIEW_FLAGGED",
  HUMAN_EDITED: "HUMAN_EDITED",
  HUMAN_APPROVED: "HUMAN_APPROVED",
  HUMAN_REJECTED: "HUMAN_REJECTED",
  AUTO_APPROVED: "AUTO_APPROVED",
} as const;

export type LearningEventType =
  (typeof LEARNING_EVENT_TYPES)[keyof typeof LEARNING_EVENT_TYPES];

export const LEARNING_OUTCOMES = {
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EDITED_AND_APPROVED: "EDITED_AND_APPROVED",
  DISMISSED: "DISMISSED",
} as const;

export type LearningOutcome =
  (typeof LEARNING_OUTCOMES)[keyof typeof LEARNING_OUTCOMES];

export const DELIVERABILITY_EVENT_TYPES = {
  BOUNCE: "BOUNCE",
  SOFT_BOUNCE: "SOFT_BOUNCE",
  HARD_BOUNCE: "HARD_BOUNCE",
  SPAM_COMPLAINT: "SPAM_COMPLAINT",
  UNSUBSCRIBE: "UNSUBSCRIBE",
  DELIVERY_FAILURE: "DELIVERY_FAILURE",
  DOMAIN_BLOCKED: "DOMAIN_BLOCKED",
} as const;

export type DeliverabilityEventType =
  (typeof DELIVERABILITY_EVENT_TYPES)[keyof typeof DELIVERABILITY_EVENT_TYPES];

export const DOMAIN_HEALTH_THRESHOLDS = {
  BOUNCE_RATE_WARNING: 0.05,
  BOUNCE_RATE_DEGRADED: 0.1,
  BOUNCE_RATE_BLOCKED: 0.2,
  COMPLAINT_RATE_WARNING: 0.002,
  COMPLAINT_RATE_DEGRADED: 0.005,
  COMPLAINT_RATE_BLOCKED: 0.01,
} as const;

export const FREE_EMAIL_HOSTS = new Set([
  "gmail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "icloud.com",
  "protonmail.com",
  "aol.com",
]);

export const API_BASE =
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";

export const CROSS_SYSTEM_SEND_COORDINATION_GUARD_HOURS = 48;