-- Add missing CAS version columns that were in schema but not yet in DB

ALTER TABLE "Campaign"
  ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "Lead"
  ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "leadStateVersion" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "OutreachMessage"
  ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "claimVersion" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "claimExpiresAt" TIMESTAMPTZ;
