export const LINKEDIN_DISCOVERY_CONFIG = {
    MIN_DELAY_MS: 20_000,
    MAX_DELAY_MS: 45_000,
    MAX_PAGES_PER_QUERY: 3,
    DEFAULT_RATE_LIMIT_BACKOFF_MS: 90_000,
    SCORE_BATCH_SIZE: 20,
    LEAD_PERSISTENCE_CONCURRENCY: 5,
    PROGRESS_EMIT_THRESHOLD_PCT: 10,
} as const;