DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'LeadState') THEN
    CREATE TYPE "LeadState" AS ENUM ('DISCOVERED','RESEARCH_PENDING','ENRICHING','ENRICHED','SIGNALS_EVALUATED','SCORE_PENDING','SCORED','EMAIL_REVEAL_PENDING','EMAIL_REVEALED','EMAIL_VALIDATING','EMAIL_VERIFIED','CONTENT_PENDING','CONTENT_READY','COMPLIANCE_PENDING','SEND_ELIGIBLE','QUEUED','SENT','WAITING_FOR_REPLY','REPLIED','DISQUALIFIED','SUPPRESSED','UNSUBSCRIBED','BOUNCED','COMPLAINT','SEQUENCE_STOPPED','MEETING_BOOKED','CONVERTED','FAILED_RETRYABLE','FAILED_TERMINAL');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EmailValidationStatus') THEN
    CREATE TYPE "EmailValidationStatus" AS ENUM ('UNKNOWN','REVEALED','VALID','INVALID','RISKY','CATCH_ALL');
  END IF;
END $$;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "leadState" "LeadState" NOT NULL DEFAULT 'DISCOVERED', ADD COLUMN IF NOT EXISTS "emailValidationStatus" "EmailValidationStatus" NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE "OutreachMessage" ADD COLUMN IF NOT EXISTS "payloadHash" TEXT, ADD COLUMN IF NOT EXISTS "complianceStatus" TEXT;
